---
title: "EC_figure"
author: "Ben Thomson"
date: "8/9/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, include = T, results = T, cache = FALSE, fig.width = 8, fig.height = 6, 
                      warning = FALSE, message = FALSE, cache.lazy = FALSE, tidy=TRUE, tidy.opts=list(arrow=TRUE, indent=2, width.cutoff=60))
  
#Load libraries

  library(Seurat)
  library(dplyr)
  library(gdata)
  library(sctransform)
  library(cowplot)
  library(patchwork)
  library(ggplot2)
  library(gridExtra)
  library(clustree)
  library(data.table)
  library(scDblFinder)
  library(future)
  library(kableExtra)
  library(intrinsicDimension)


  theme_set(theme_cowplot())
  theme(aspect.ratio=1)



#list of sex-specific features taken from Skelly et al.
#https://doi.org/10.1016/j.celrep.2017.12.072
sex.specific.features <- c("Xist", "Ddx3y", "Eif2s3y", "Erdr1", "Gm29650", "Kdm5d", "Uty")

bad.features <- c("Angpt1", sex.specific.features)




```


```{r}

  ec.dataset  <- readRDS("../data/6wk_endos_10-1-20.rds.gz")
  lec.dataset <- readRDS("../data/6wk_LECs_10-1-20.rds.gz")

```

```{r panel.a}

  panel.a <- RenameIdents(ec.dataset, 'SC' = "EC_1", 'LEC' = "EC_1")

  panel.a.fig.wt <- DimPlot(object = subset(panel.a, subset = genotype == "WT"), 
                            reduction = "umap", label = TRUE, pt.size = 0.5, label.size = 4)  +
    NoLegend() + coord_fixed() + theme(aspect.ratio=1) + 
    theme(axis.line = element_line(color="black", size = 0.7)) +
    theme(axis.title = element_text(size = 10)) +
    ylim(c(-4,7))
  
  panel.a.fig.ko <- DimPlot(object = subset(panel.a, subset = genotype == "KO"), 
                            reduction = "umap", label = TRUE, pt.size = 0.5, label.size = 4)  +
    NoLegend() + coord_fixed() + theme(aspect.ratio=1) + 
    theme(axis.line = element_line(color="black", size = 0.7)) +
    theme(axis.line.y = element_blank(), axis.ticks.y = element_blank(), axis.text.y = element_blank()) +
    theme(axis.title.x = element_text(size = 10)) +
    theme(axis.title.y = element_blank()) +
    ylim(c(-4,7))

  

  panel.a.fig.wt + panel.a.fig.ko
  
  pdf(file = "../figures/EC_figure_a.pdf", width = 5, height = 2)
  plot(panel.a.fig.wt + panel.a.fig.ko)
  dev.off()


```


```{r panel.b}

  panel.b <- RenameIdents(ec.dataset, 'SC' = "EC_1", 'LEC' = "EC_1")

  plot.list.b <- VlnPlot(panel.b, assay = "RNA", features = c("Ccl21a", "Vwf", "Kdr", "Plvap", "Prox1", "Ihh","Ptprb", "Tek", "Sox17"), 
                         pt.size = 0, combine = F)
  
  for(i in seq_along(plot.list.b)) {
   plot.list.b[[i]] <- plot.list.b[[i]] +
      theme(axis.ticks= element_blank(), axis.text.y = element_blank(), 
            axis.title.x = element_blank()) +
            theme(title = element_text(family = "sans", face = "italic")) +
            theme(axis.line = element_line(size = 0.7)) +
            NoLegend() +
            scale_y_continuous(expand = c(0, 0)) +
            theme(aspect.ratio=0.3) +
            theme(axis.title.y = element_blank())
   
   if(i > (length(plot.list.b) - 3)) {
     plot.list.b[[i]] <- plot.list.b[[i]] +
       theme(axis.text.x = element_text())
    } else {
     plot.list.b[[i]] <- plot.list.b[[i]] +
      theme(axis.text.x = element_blank())
   }
   
 }
  
  wrap_plots(plot.list.b)
  
  pdf(file = "../figures/EC_figure_b.pdf", width = 5, height = 5)
  plot(wrap_plots(plot.list.b))
  dev.off()
  

```


```{r panel.c}

  panel.c <- lec.dataset

  panel.c.fig.wt <- DimPlot(object = subset(panel.c, subset = genotype == "WT"), reduction = "umap", label = TRUE, 
                    pt.size = 0.5, label.size = 4)  +
    NoLegend() + coord_fixed() + theme(aspect.ratio=1) + 
    theme(axis.line = element_line(color="black", size = 0.7)) +
    theme(axis.title = element_text(size = 10)) +
    xlim(c(-6,3)) + ylim(c(-5,5))
  
  panel.c.fig.ko <- DimPlot(object = subset(panel.c, subset = genotype == "KO"), reduction = "umap", label = TRUE, 
                    pt.size = 0.5, label.size = 4)  +
    NoLegend() + coord_fixed() + theme(aspect.ratio=1) + 
    theme(axis.line = element_line(color="black", size = 0.7)) +
    theme(axis.line.y = element_blank(), axis.ticks.y = element_blank(), axis.text.y = element_blank()) +
    theme(axis.title.x = element_text(size = 10)) +
    theme(axis.title.y = element_blank()) +
    xlim(c(-6,3)) + ylim(c(-5,5))

  
  panel.c.fig.wt + panel.c.fig.ko
  
  pdf(file = "../figures/EC_figure_c.pdf", width = 5, height = 2)
  plot(panel.c.fig.wt + panel.c.fig.ko)
  dev.off()

```

```{r panel.d}

  panel.d <- RenameIdents(ec.dataset, 'EC_2' = "BEC", 'EC_3' = "BEC", 'EC_4' = "BEC")
  panel.d@active.ident <- factor(x = panel.d@active.ident, levels = c("BEC", "LEC", "SC"))

  plot.list.d <- VlnPlot(panel.d, assay = "RNA", 
                         features = c("Prox1","Lyve1", "Pdpn", "Flt1", "Kdr", "Flt4", "Plvap", "Tek", 
                                      "Ptprb", "Itga5", "Itga6", "Itga9", "Itgb1"), 
                         pt.size = 0, combine = FALSE)
  
  for(i in seq_along(plot.list.d)) {
   plot.list.d[[i]] <- plot.list.d[[i]] +
      theme(axis.ticks= element_blank(), axis.text.y = element_blank(), 
            axis.title.x = element_blank()) +
            theme(title = element_text(family = "sans", face = "italic")) +
            theme(axis.line = element_line(size = 0.7)) +
            NoLegend() +
            scale_y_continuous(expand = c(0, 0)) +
            theme(aspect.ratio=0.3) +
            theme(axis.title.y = element_blank())
   
   if(i > (length(plot.list.d) - 3)) {
     plot.list.d[[i]] <- plot.list.d[[i]] +
       theme(axis.text.x = element_text())
    } else {
     plot.list.d[[i]] <- plot.list.d[[i]] +
      theme(axis.text.x = element_blank())
   }
   
 }
  
  wrap_plots(plot.list.d, ncol = 3)
  
  pdf(file = "../figures/EC_figure_d.pdf", width = 5, height = 6)
  plot(wrap_plots(plot.list.d, ncol = 3))
  dev.off()


```

```{r panel.e, fig.width=4, fig.height=4}

  boot.data <- FetchData(subset(ec.dataset, subset = genotype == "WT"), vars = "ident")$ident
  ko.data <-  FetchData(subset(ec.dataset, subset = genotype == "KO"), vars = "ident")$ident
  
  pct.gt <- function(data, value) {
    total <- length(data)
    selected <- length(data[data==value])
    return (selected / total)
  }
  
  nboots <- 10000
  boot.result <- numeric(nboots)
  set.seed(42)
  
  #number of KO endothelial cells
  sample.size = length(ko.data)
  
  for(i in 1:nboots) {
    boot.sample <- sample(boot.data, sample.size, replace = TRUE)
    boot.result[i] <- pct.gt(boot.sample, "SC")
  }
  
  hist(boot.result)
  quantile(boot.result, c(0.025, 0.975))
  mean(boot.result)
  


  bar.data <- data.frame(row.names = c("WT", "KO"))
  KO <- pct.gt(ko.data, "SC")
  WT <- boot.result
  
  bar.data <- data.frame(WT, KO)
  bar.data <- melt(bar.data, value.name = "percent.sc")
  
  

  p1 <- ggplot(data = bar.data, aes(x=variable, y=percent.sc, fill=variable, width = 1.5)) + geom_violin() +

    
    theme(axis.line = element_line(size = 0.7)) +
    theme(axis.ticks.y = element_line(size = 0.7), axis.ticks.x = element_blank()) +
    theme(aspect.ratio = 2.5)

  p1 <- p1 + scale_fill_manual(values = c("#00bfc4", "#f8766d")) 
  p1 <- p1 + scale_y_continuous(expand = c(0, 0), limits = c(0, 0.3), breaks = c(0,0.1,0.2,0.3))


  plot(p1)
  
  pdf(file = "../figures/EC_figure_e.pdf", width = 4, height = 4)
  plot(p1)
  dev.off()



```

```{r panel.g, fig.width=8, fig.height=4}

  panel.g <- ec.dataset
  panel.g@active.ident <- factor(x = panel.g@active.ident, levels = c("EC_4", "EC_3", "EC_2", "LEC", "SC"))
  genelist <- read.csv("../figures/genes_for_ec_heatmap.csv", stringsAsFactors = F, fileEncoding="UTF-8-BOM")$gene
  
  dot <- DotPlot(panel.g, features = genelist, assay = "RNA", dot.scale = 7.5, dot.min = 0.05) +
    theme(axis.line = element_line(size = 0.7)) +
    theme(aspect.ratio = 0.25) +
    theme(axis.text.x = element_text(angle = 45, face = "italic", vjust = 1, hjust = 1)) +
    theme(axis.text.y = element_text(size = 14))
  
  plot(dot)
  
  pdf(file = "../figures/EC_figure_g.pdf", width = 8, height = 4)
  plot(dot)
  dev.off()


```

```{r panel.f}

  panel.f <- BuildClusterTree(ec.dataset, assay = "RNA", reorder = T)
  PlotClusterTree(panel.f)
  
  pdf(file = "../figures/EC_figure_f.pdf", width = 4, height = 4)
  PlotClusterTree(panel.f)
  dev.off()



```

The data from Panel C was also used to generate Supplemental figure 7. 

```{r SuppFig7}

  supp.fig.7 <- FeaturePlot(panel.c, features = c("Cdh5", "Prox1", "Lyve1", "Pdpn", "Ccl21a", "Selp"), ncol = 3)

  plot(supp.fig.7)
  
  pdf(file = "../figures/Supp_Fig_7.pdf", width = 7, height = 4)
  plot(supp.fig.7)
  dev.off()

```